### ISSUE TITLE
SDL hangs all event processing on window move, causing ImGui to crash

### ISSUE THREAD

**Issue by DarkContact** [mosra/magnum-integration#57]
If you try to drag the window, the application will crash with an error: Expression: (g.IO.DeltaTime > 0.0f || g.FrameCount == 0) && "Need a positive DeltaTime!"

https://github.com/mosra/magnum-integration/blob/master/src/Magnum/ImGuiIntegration/Context.cpp#L252 io.DeltaTime can be zero.

Possible fix: 
if (io.DeltaTime == 0.0f) { io.DeltaTime = 0.0000001f; }
but looks creepy

**Comment by mosra** [comment]
Interesting. What's the platform / compiler you're on? Is it possible that the app is running at more than 60 FPS (indicating broken VSync, probably) which is causing the delta time to be very close to zero?

**Comment by DarkContact** [comment]
Windows / MinGW 7.3.0
VSync on
![image](https://user-images.githubusercontent.com/2587074/67892712-57d00f80-fb66-11e9-96bf-b5d1c1c3b2c2.png)

**Comment by mosra** [comment]
> If you try to drag the window

Ah! Now I see -- you mean dragging the application window, not the ImGui windows, right? This could be because, IIRC, on Windows each window drag triggers a repaint for some reason, causing `drawEvent()` to be called much more than @ 60 FPS.

I'll need to investigate why this frequent redraw is done, if it's needed at all and how ImGui itself handles this in its own examples. Thanks for the report, I'll ping you back once I have something.

**Comment by DarkContact** [comment]
Yes, I mean application window. Ok. Thanks.

**Comment by mosra** [comment]
Unfortunately I don't really have a solution for this. SDL has a [Window-specific bug/misfeature](https://bugzilla.libsdl.org/show_bug.cgi?id=2077), reported back in 2014 and not fixed since, where it hangs all event processing for the time where you drag or resize the window. After that, it flushes the event queue, causing repaint events and everything else to happen immediately after each other. That ImGui crashes is only a consequence, it's very likely to cause serious misbehavior elsewhere as well -- I hit this most recently with mosra/magnum#423 when trying to implement DPI scaling change events, there it delays the window resize to when you release the mouse again, not nice.

I am monitoring that bug, hoping *something* will happen in this decade at least. 

Two suggestions -- either don't drag windows with ImGui in it, or switch to GlfwApplication, GLFW doesn't suffer from this problem at all.

**Comment by mosra** [comment]
Worked around in e7dc17a7e32f4a0ef3a66cffaf1d41c485d1245c basically the same way you suggested -- there's nothing happening about this at on the SDL side at all (the bug is milestoned for SDL 2.1, who knows when that happens), so let's do a fix here instead.

**Comment by Squareys** [comment]
https://github.com/libsdl-org/SDL/issues/1059 was fixed very recently in SDL 2.30.
